version: "0.0.2"
reload-message: "&aConfig successfully reloaded"
permissions:
  reload: "pastimegames.reload"
commands:
  noPermission: "&cYou have no permission to run this command"
  wrongSyntax: "&cWrong syntax"
connect4:
  invTitle: "Connect 4:"
tictactoe:
  invTitle: "TicTacToe:"
items:
  placeholder:
    displayName: " "
  yourTurn:
    displayName: "&aYour turn"
  opponentsTurn:
    displayName: "&fWait for your opponent to make a move"
  yourChipItem:
    displayName: " "
  opponentsChipItem:
    displayName: " "
