#Configfile of PastimeGames - change settings here
#If any setting is wrong the default will be used
#DON'T CHANGE VERSION
version: "0.0.1"
reload-message: "&aConfig successfully reloaded"
connectfour:
  invTitle: "Connect 4:"
  items:
    placeholder:
      displayName: ""
    yourTurn:
      displayName: "&aYour turn"
    opponentsTurn:
      displayName: "&fWait for your opponent to make a move"
    yourChipItem:
      displayName: ""
    opponentsChipItem:
      displayName: ""
